export const LOCAL_DATABASE_EXTRACTION_SKILLS = [
  'medhelp-database-api-access',
  'cfps-skill',
  'cgss-skill',
  'charls-skill',
  'class-skill',
  'chfs-skill',
  'chip-skill',
  'chns-skill',
  'clds-skill',
  'clhls-skill',
  'css-skill',
  'share-skill',
  'hrs-skill',
  'elsa-skill',
  'klosa-skill',
  'lasi-skill',
  'mhas-skill',
  'ukb-skill',
  'nhanes-skill',
  'mimiciii-skill',
  'mimiciv-skill',
  'mimiciv31-skill',
  'nwicu-skill',
  'eicu-skill',
  'sicdb-skill',
  'pic-skill',
  'inspire-skill',
  'seer-skill',
  'datacommons-client',
  'geo-database',
] as const;

export const LOCAL_DATABASE_ANALYSIS_SKILLS = [
  'easyukb-analysis',
  'gco-database-analysis',
] as const;
